In [1]:
import numpy as np

In [2]:
a = np.reshape(np.linspace(0,35,36),(6,6))
a

array([[  0.,   1.,   2.,   3.,   4.,   5.],
       [  6.,   7.,   8.,   9.,  10.,  11.],
       [ 12.,  13.,  14.,  15.,  16.,  17.],
       [ 18.,  19.,  20.,  21.,  22.,  23.],
       [ 24.,  25.,  26.,  27.,  28.,  29.],
       [ 30.,  31.,  32.,  33.,  34.,  35.]])

In [22]:
b = np.reshape(np.linspace(0,63,64),(4,16))
b

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.],
       [ 16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,  25.,  26.,
         27.,  28.,  29.,  30.,  31.],
       [ 32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,
         43.,  44.,  45.,  46.,  47.],
       [ 48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,
         59.,  60.,  61.,  62.,  63.]])

In [24]:
def morton(matrix):
    A = []
    nx = len(matrix)
    ny = len(matrix[0])
    for i in range(0,nx,2):
        for j in range(0,ny,2):
            A.append(matrix[i,j])
            A.append(matrix[i,j+1])
            A.append(matrix[i+1,j])
            A.append(matrix[i+1,j+1])
    return A

In [25]:
A = morton(a)
A

[0.0,
 1.0,
 6.0,
 7.0,
 2.0,
 3.0,
 8.0,
 9.0,
 4.0,
 5.0,
 10.0,
 11.0,
 12.0,
 13.0,
 18.0,
 19.0,
 14.0,
 15.0,
 20.0,
 21.0,
 16.0,
 17.0,
 22.0,
 23.0,
 24.0,
 25.0,
 30.0,
 31.0,
 26.0,
 27.0,
 32.0,
 33.0,
 28.0,
 29.0,
 34.0,
 35.0]

In [26]:
B = morton(b)
B

[0.0,
 1.0,
 16.0,
 17.0,
 2.0,
 3.0,
 18.0,
 19.0,
 4.0,
 5.0,
 20.0,
 21.0,
 6.0,
 7.0,
 22.0,
 23.0,
 8.0,
 9.0,
 24.0,
 25.0,
 10.0,
 11.0,
 26.0,
 27.0,
 12.0,
 13.0,
 28.0,
 29.0,
 14.0,
 15.0,
 30.0,
 31.0,
 32.0,
 33.0,
 48.0,
 49.0,
 34.0,
 35.0,
 50.0,
 51.0,
 36.0,
 37.0,
 52.0,
 53.0,
 38.0,
 39.0,
 54.0,
 55.0,
 40.0,
 41.0,
 56.0,
 57.0,
 42.0,
 43.0,
 58.0,
 59.0,
 44.0,
 45.0,
 60.0,
 61.0,
 46.0,
 47.0,
 62.0,
 63.0]

In [10]:
def group (list1, n):
    """Function sorts an input array into a n groups"""
    length = len(list1)
    n1 = int(length/n)                   #no. of elements per block
    j = 0
    A = np.empty((n,n1))
    if np.mod(length,n) == 0:
        for i in range (length):
            A[j,np.mod(i,n1)] = list1[i]
            if np.mod(i+1,n1) == 0:
                j += 1
    if np.mod(length,n) != 0
        n1 = 
    return A

In [11]:
sorted_list = group (A,6)

In [12]:
sorted_list

array([[  0.,   1.,   6.,   7.,   2.,   3.],
       [  8.,   9.,   4.,   5.,  10.,  11.],
       [ 12.,  13.,  18.,  19.,  14.,  15.],
       [ 20.,  21.,  16.,  17.,  22.,  23.],
       [ 24.,  25.,  30.,  31.,  26.,  27.],
       [ 32.,  33.,  28.,  29.,  34.,  35.]])

In [16]:
sorted_listb

array([[  0.,   1.,   8.,   9.,   2.,   3.,  10.,  11.],
       [  4.,   5.,  12.,  13.,   6.,   7.,  14.,  15.],
       [ 16.,  17.,  24.,  25.,  18.,  19.,  26.,  27.],
       [ 20.,  21.,  28.,  29.,  22.,  23.,  30.,  31.],
       [ 32.,  33.,  40.,  41.,  34.,  35.,  42.,  43.],
       [ 36.,  37.,  44.,  45.,  38.,  39.,  46.,  47.],
       [ 48.,  49.,  56.,  57.,  50.,  51.,  58.,  59.],
       [ 52.,  53.,  60.,  61.,  54.,  55.,  62.,  63.]])